name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
        exclude:
          - os: macos-latest
            compiler: g++

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Make
      run: make

    - name: Test basic functionality
      run: |
        timeout 5s ./server &
        sleep 2
        curl -f http://localhost:8080/api/health || exit 1